In [299]:
# Initial imports
import os
import pandas as pd
from dotenv import load_dotenv
import nltk as nltk
from wordcloud import WordCloud
nltk.download('vader_lexicon')
from nltk.sentiment.vader import SentimentIntensityAnalyzer
analyzer = SentimentIntensityAnalyzer()
from newsapi import NewsApiClient
load_dotenv()
import alpaca_trade_api as tradeapi
import numpy as np

%matplotlib inline

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\bfode\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!


In [300]:
# Set Alpaca API key and secret
# YOUR CODE HERE!
alpaca_api_key = os.getenv("ALPACA_API_KEY")
alpaca_secret_key = os.getenv("ALPACA_SECRET_KEY")

# Create the Alpaca API object
# YOUR CODE HERE!
alpaca = tradeapi.REST(
    alpaca_api_key,
    alpaca_secret_key,
    api_version="v2")

In [301]:
# Format current date as ISO format
# YOUR CODE HERE!

start_date = pd.Timestamp('2015-08-07', tz='America/New_York').isoformat()
end_date = pd.Timestamp('2020-08-07', tz='America/New_York').isoformat()
#today = pd.Timestamp("2021-04-12", tz="America/New_York").isoformat()

# Set the tickers
tickers = ["WFC", "GS","MS","SPY"]

# Set timeframe to '1D' for Alpaca API
timeframe = "1D"

# Get current closing prices for SPY and AGG
# YOUR CODE HERE!
df_portfolio = alpaca.get_barset(
    tickers,
    timeframe,
    start = start_date,
    end = end_date
).df

# Preview DataFrame
# YOUR CODE HERE!
df_portfolio.tail()

GS                                         MS  \
                             open      high      low   close   volume   open   
2020-08-03 00:00:00-04:00  198.49  199.8800  196.530  199.39  3200674  49.22   
2020-08-04 00:00:00-04:00  199.35  201.7200  198.475  201.65  3688146  49.50   
2020-08-05 00:00:00-04:00  203.17  204.8075  203.010  204.48  4081429  49.59   
2020-08-06 00:00:00-04:00  205.00  206.2900  203.830  204.25  3310894  49.83   
2020-08-07 00:00:00-04:00  203.48  208.8000  202.450  208.27  5694814  49.21   

                                                                SPY          \
                             high    low  close    volume      open    high   
2020-08-03 00:00:00-04:00  49.905  48.72  49.47   8618979  328.3200  329.62   
2020-08-04 00:00:00-04:00  49.770  49.08  49.26  11431220  327.8600  330.06   
2020-08-05 00:00:00-04:00  49.960  49.44  49.78  11876099  331.4700  332.39   
2020-08-06 00:00:00-04:00  49.980  49.24  49.46  10097493  331.4799  334.46   
2020-08-07 00:00:00-04:00  50.470  49.08  50.35  11121376  333.2800  334.88   

                                                       WFC                \
                              low   close    volume   open   high    low   
2020-08-03 00:00:00-04:00  327.73  328.76  71741125  24.25  24.50  23.90   
2020-08-04 00:00:00-04:00  327.86  330.03  73684427  24.20  24.29  24.03   
2020-08-05 00:00:00-04:00  331.18  332.06  72846458  24.40  24.75  24.34   
2020-08-06 00:00:00-04:00  331.13  334.31  76900649  24.20  24.50  24.12   
2020-08-07 00:00:00-04:00  332.30  334.55  98710236  24.13  25.22  24.00   

                                            
                           close    volume  
2020-08-03 00:00:00-04:00  24.30  42432609  
2020-08-04 00:00:00-04:00  24.22  53890753  
2020-08-05 00:00:00-04:00  24.39  60804684  
2020-08-06 00:00:00-04:00  24.25  75647696  
2020-08-07 00:00:00-04:00  25.07  77686591

In [302]:
#Saving Raw data to Raw Data Folder
df_portfolio.to_csv('../../data/cleandata/df_portfolio.csv')

In [303]:
# Get 3 years' worth of historical data for SPY and AGG
#Wells Fargo Co. (WFC), Goldman Sachs Group Inc. (GS), and Morgan Stanley (MS).

# Format current date as ISO format
start_date = pd.Timestamp('2019-01-01', tz='America/New_York').isoformat()
end_date = pd.Timestamp('2021-06-30', tz='America/New_York').isoformat()
tickers = ["WFC", "GS","MS","SPY"]

# Set timeframe to '1D' for Alpaca API
timeframe = "1D"

df_stock_data = alpaca.get_barset(
    tickers,
    timeframe,
    start=start_date,
    end=end_date,
    limit=1000,
).df

# Display sample data
df_stock_data.head()

GS                                          MS  \
                             open      high     low     close   volume   open   
2019-01-02 00:00:00-05:00  164.33  172.2500  163.35  171.5600  3592312  39.02   
2019-01-03 00:00:00-05:00  170.66  171.7700  168.29  169.6300  3462254  40.22   
2019-01-04 00:00:00-05:00  172.99  176.0000  171.10  175.4901  2794038  40.50   
2019-01-07 00:00:00-05:00  175.23  177.8250  172.27  176.0700  2609770  41.51   
2019-01-08 00:00:00-05:00  177.78  178.0999  172.90  175.3200  2306569  42.30   

                                                              SPY          \
                            high    low   close    volume    open    high   
2019-01-02 00:00:00-05:00  40.72  38.76  40.305   9225170  245.98  251.21   
2019-01-03 00:00:00-05:00  40.22  39.25  39.675  10212075  248.23  248.57   
2019-01-04 00:00:00-05:00  41.58  40.28  41.555  10212613  247.59  253.11   
2019-01-07 00:00:00-05:00  42.16  40.98  41.770  10626187  252.69  255.95   
2019-01-08 00:00:00-05:00  42.41  41.08  41.435   9944602  256.82  257.31   

                                                         WFC                 \
                              low   close     volume    open    high    low   
2019-01-02 00:00:00-05:00  245.95  249.89  107236613  45.525  46.930  45.41   
2019-01-03 00:00:00-05:00  244.03  244.46  113782919  46.650  47.345  46.37   
2019-01-04 00:00:00-05:00  247.17  252.41  122528832  47.420  48.110  47.20   
2019-01-07 00:00:00-05:00  251.69  254.40   88317608  47.780  48.230  47.54   
2019-01-08 00:00:00-05:00  254.00  256.65   88864452  47.900  48.160  46.92   

                                             
                            close    volume  
2019-01-02 00:00:00-05:00  46.865  16553465  
2019-01-03 00:00:00-05:00  46.655  19953966  
2019-01-04 00:00:00-05:00  47.915  19804914  
2019-01-07 00:00:00-05:00  47.715  17632046  
2019-01-08 00:00:00-05:00  47.540  16653807

In [304]:
df_stock_data.to_csv('../../data/Rawdata/df_stock_data.csv')

In [305]:
df_stock_data.isnull().sum()

GS   open      0
     high      0
     low       0
     close     0
     volume    0
MS   open      0
     high      0
     low       0
     close     0
     volume    0
SPY  open      0
     high      0
     low       0
     close     0
     volume    0
WFC  open      0
     high      0
     low       0
     close     0
     volume    0
dtype: int64

In [306]:
df_stock_data.dropna(inplace=True)
df_stock_data

GS                                         \
                             open      high       low     close   volume   
2019-01-02 00:00:00-05:00  164.33  172.2500  163.3500  171.5600  3592312   
2019-01-03 00:00:00-05:00  170.66  171.7700  168.2900  169.6300  3462254   
2019-01-04 00:00:00-05:00  172.99  176.0000  171.1000  175.4901  2794038   
2019-01-07 00:00:00-05:00  175.23  177.8250  172.2700  176.0700  2609770   
2019-01-08 00:00:00-05:00  177.78  178.0999  172.9000  175.3200  2306569   
...                           ...       ...       ...       ...      ...   
2021-06-24 00:00:00-04:00  363.00  370.8800  362.7800  368.7300  2276831   
2021-06-25 00:00:00-04:00  370.60  371.1499  364.5400  368.6700  2176947   
2021-06-28 00:00:00-04:00  368.03  368.8700  363.8600  368.5950  1491640   
2021-06-29 00:00:00-04:00  374.75  378.0900  370.7495  372.6200  2151889   
2021-06-30 00:00:00-04:00  370.90  380.1100  370.9000  379.4450  1823472   

                              MS                                      SPY  \
                            open   high     low   close    volume    open   
2019-01-02 00:00:00-05:00  39.02  40.72  38.760  40.305   9225170  245.98   
2019-01-03 00:00:00-05:00  40.22  40.22  39.250  39.675  10212075  248.23   
2019-01-04 00:00:00-05:00  40.50  41.58  40.280  41.555  10212613  247.59   
2019-01-07 00:00:00-05:00  41.51  42.16  40.980  41.770  10626187  252.69   
2019-01-08 00:00:00-05:00  42.30  42.41  41.080  41.435   9944602  256.82   
...                          ...    ...     ...     ...       ...     ...   
2021-06-24 00:00:00-04:00  86.62  87.39  85.835  87.080   6886244  424.89   
2021-06-25 00:00:00-04:00  87.30  88.62  86.720  88.400   8274607  425.90   
2021-06-28 00:00:00-04:00  88.25  88.20  86.430  87.700   5089844  427.17   
2021-06-29 00:00:00-04:00  91.20  91.63  89.780  90.640  14238151  427.89   
2021-06-30 00:00:00-04:00  90.17  91.91  90.130  91.680   8166030  427.20   

                                                                   WFC  \
                               high     low   close     volume    open   
2019-01-02 00:00:00-05:00  251.2100  245.95  249.89  107236613  45.525   
2019-01-03 00:00:00-05:00  248.5700  244.03  244.46  113782919  46.650   
2019-01-04 00:00:00-05:00  253.1100  247.17  252.41  122528832  47.420   
2019-01-07 00:00:00-05:00  255.9500  251.69  254.40   88317608  47.780   
2019-01-08 00:00:00-05:00  257.3100  254.00  256.65   88864452  47.900   
...                             ...     ...     ...        ...     ...   
2021-06-24 00:00:00-04:00  425.5500  424.62  425.09   39863529  44.260   
2021-06-25 00:00:00-04:00  427.0943  425.55  426.57   50460394  45.540   
2021-06-28 00:00:00-04:00  427.6500  425.89  427.48   43937373  46.000   
2021-06-29 00:00:00-04:00  428.5600  427.13  427.68   32097572  46.000   
2021-06-30 00:00:00-04:00  428.7800  427.18  428.08   46776402  44.660   

                                                             
                             high    low    close    volume  
2019-01-02 00:00:00-05:00  46.930  45.41  46.8650  16553465  
2019-01-03 00:00:00-05:00  47.345  46.37  46.6550  19953966  
2019-01-04 00:00:00-05:00  48.110  47.20  47.9150  19804914  
2019-01-07 00:00:00-05:00  48.230  47.54  47.7150  17632046  
2019-01-08 00:00:00-05:00  48.160  46.92  47.5400  16653807  
...                           ...    ...      ...       ...  
2021-06-24 00:00:00-04:00  45.420  44.20  45.1800  25321028  
2021-06-25 00:00:00-04:00  46.650  45.22  46.3701  34592273  
2021-06-28 00:00:00-04:00  46.070  45.09  45.7900  23729482  
2021-06-29 00:00:00-04:00  46.380  44.60  44.8000  26581925  
2021-06-30 00:00:00-04:00  45.385  44.45  45.2900  14547897  

[629 rows x 20 columns]

In [307]:
df_stock_data.to_csv('../../data/cleandata/df_stock_data.csv')

In [308]:
closing_price_gs = pd.DataFrame(df_stock_data["GS"]["close"])
closing_price_ms = pd.DataFrame(df_stock_data["MS"]["close"])
closing_price_wfc = pd.DataFrame(df_stock_data["WFC"]["close"])
closing_price_spy = pd.DataFrame(df_stock_data["SPY"]["close"])
all_closing_price = pd.concat([closing_price_gs, closing_price_ms, closing_price_wfc, closing_price_spy], axis="columns", join="inner")
all_closing_price.index = all_closing_price.index.date
all_closing_price.columns = ["WFC", "GS","MS","SPY"]
all_closing_price

WFC      GS       MS     SPY
2019-01-02  171.5600  40.305  46.8650  249.89
2019-01-03  169.6300  39.675  46.6550  244.46
2019-01-04  175.4901  41.555  47.9150  252.41
2019-01-07  176.0700  41.770  47.7150  254.40
2019-01-08  175.3200  41.435  47.5400  256.65
...              ...     ...      ...     ...
2021-06-24  368.7300  87.080  45.1800  425.09
2021-06-25  368.6700  88.400  46.3701  426.57
2021-06-28  368.5950  87.700  45.7900  427.48
2021-06-29  372.6200  90.640  44.8000  427.68
2021-06-30  379.4450  91.680  45.2900  428.08

[629 rows x 4 columns]

In [309]:

covid_data = pd.read_csv('covid_cases.csv', index_col="Date", parse_dates=True, infer_datetime_format=True)

##covid_data.sort_index(ascending = True, inplace = True)
covid_data.tail()


New Cases  7-Day Moving Avg  Historic Cases
Date                                                   
2020-01-26          3                 6               0
2020-01-25          3                 5               0
2020-01-24          1                 5               0
2020-01-23          2                 5               0
2020-01-22         33                 4               0

In [377]:
df_close_covid = all_closing_price.join(covid_data["New Cases"])
df_close_covid.dropna(inplace=True)

In [378]:
df_close_covid.shape[0]*.7

254.79999999999998

In [379]:
df_close_covid.iloc[253]

WFC             289.28
GS               74.13
MS               31.90
SPY             382.86
New Cases    190800.00
Name: 2021-01-22 00:00:00, dtype: float64

In [380]:
def window_data(df, window, feature_col_number, target_col_number):
    X = []
    y = []
    for i in range(len(df) - window):
        features = df.iloc[i : (i + window), feature_col_number]
        target = df.iloc[(i + window), target_col_number]
        X.append(features)
        y.append(target)
    return np.array(X), np.array(y).reshape(-1, 1)

In [381]:
window_size = 10
feature_column = 2
target_column = 1
X, y = window_data(df_close_covid, window_size, feature_column, target_column)
print (f"X sample values:\n{X[:5]} \n")
print (f"y sample values:\n{y[:5]}")

X sample values:
[[48.56 48.23 47.57 47.09 47.36 47.27 47.9  46.91 47.11 47.27]
 [48.23 47.57 47.09 47.36 47.27 47.9  46.91 47.11 47.27 48.31]
 [47.57 47.09 47.36 47.27 47.9  46.91 47.11 47.27 48.31 47.98]
 [47.09 47.36 47.27 47.9  46.91 47.11 47.27 48.31 47.98 47.85]
 [47.36 47.27 47.9  46.91 47.11 47.27 48.31 47.98 47.85 47.77]] 

y sample values:
[[54.995]
 [55.01 ]
 [55.03 ]
 [55.35 ]
 [55.77 ]]


In [382]:
split = int(0.7 * len(X))
X_train = X[: split]
X_test = X[split :]
y_train = y[: split]
y_test = y[split :]
X_train

array([[48.56, 48.23, 47.57, ..., 46.91, 47.11, 47.27],
       [48.23, 47.57, 47.09, ..., 47.11, 47.27, 48.31],
       [47.57, 47.09, 47.36, ..., 47.27, 48.31, 47.98],
       ...,
       [33.19, 33.24, 33.93, ..., 32.43, 31.99, 31.9 ],
       [33.24, 33.93, 33.8 , ..., 31.99, 31.9 , 32.24],
       [33.93, 33.8 , 34.76, ..., 31.9 , 32.24, 31.37]])

In [383]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

In [384]:
model = Sequential()

number_units = 5
dropout_fraction = 0.2

# Layer 1
model.add(LSTM(units=number_units, return_sequences=True, input_shape=(X_train.shape[1], 1)))
model.add(Dropout(dropout_fraction))
# Layer 2
model.add(LSTM(units=number_units, return_sequences=True))
model.add(Dropout(dropout_fraction))
# Layer 3
model.add(LSTM(units=number_units))
model.add(Dropout(dropout_fraction))
# Output layer
model.add(Dense(1))

In [385]:
model.compile(optimizer="adam", loss="mean_squared_error")

In [386]:
model.summary()

Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_24 (LSTM)               (None, 10, 5)             140       
_________________________________________________________________
dropout_24 (Dropout)         (None, 10, 5)             0         
_________________________________________________________________
lstm_25 (LSTM)               (None, 10, 5)             220       
_________________________________________________________________
dropout_25 (Dropout)         (None, 10, 5)             0         
_________________________________________________________________
lstm_26 (LSTM)               (None, 5)                 220       
_________________________________________________________________
dropout_26 (Dropout)         (None, 5)                 0         
_________________________________________________________________
dense_8 (Dense)              (None, 1)                

In [387]:
model.fit(X_train, y_train, epochs=10, shuffle=False, batch_size=1, verbose=1)

Epoch 1/10


ValueError: in user code:

    C:\Users\bfode\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py:855 train_function  *
        return step_function(self, iterator)
    C:\Users\bfode\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py:845 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    C:\Users\bfode\anaconda3\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:1285 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Users\bfode\anaconda3\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2833 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Users\bfode\anaconda3\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:3608 _call_for_each_replica
        return fn(*args, **kwargs)
    C:\Users\bfode\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py:838 run_step  **
        outputs = model.train_step(data)
    C:\Users\bfode\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py:795 train_step
        y_pred = self(x, training=True)
    C:\Users\bfode\anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:1013 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
    C:\Users\bfode\anaconda3\lib\site-packages\tensorflow\python\keras\engine\input_spec.py:215 assert_input_compatibility
        raise ValueError('Input ' + str(input_index) + ' of layer ' +

    ValueError: Input 0 of layer sequential_8 is incompatible with the layer: expected ndim=3, found ndim=2. Full shape received: (1, 10)


In [388]:
model.evaluate(X_test, y_test)

ValueError: in user code:

    C:\Users\bfode\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py:1323 test_function  *
        return step_function(self, iterator)
    C:\Users\bfode\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py:1314 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    C:\Users\bfode\anaconda3\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:1285 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Users\bfode\anaconda3\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2833 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Users\bfode\anaconda3\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:3608 _call_for_each_replica
        return fn(*args, **kwargs)
    C:\Users\bfode\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py:1307 run_step  **
        outputs = model.test_step(data)
    C:\Users\bfode\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py:1266 test_step
        y_pred = self(x, training=False)
    C:\Users\bfode\anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:1013 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
    C:\Users\bfode\anaconda3\lib\site-packages\tensorflow\python\keras\engine\input_spec.py:215 assert_input_compatibility
        raise ValueError('Input ' + str(input_index) + ' of layer ' +

    ValueError: Input 0 of layer sequential_8 is incompatible with the layer: expected ndim=3, found ndim=2. Full shape received: (None, 10)


In [ ]:
predicted = model.predict(X_test)

In [ ]:
predicted_prices = scaler.inverse_transform(predicted)
real_prices = scaler.inverse_transform(y_test.reshape(-1, 1))

In [ ]:
stocks = pd.DataFrame({
    "Real": real_prices.ravel(),
    "Predicted": predicted_prices.ravel()
    }, index = data.index[-len(real_prices): ])
stocks.head(100)

In [ ]:
stocks.hvplot.line(xlabel="Date", ylabel="Price")

In [281]:
stocks.plot()

NameError: name 'stocks' is not defined